const ACTION_TYPES = {
  INCREMENT: "INCREMENT",
  INCREMENT_BY: "INCREMENT_BY",
  DECREMENT: "DECREMENT",
  SET_FILTER: "SET_FILTER",
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
};

export default ACTION_TYPES;
